development:
  dialect: postgres
  datasource: host=localhost dbname=postgres user=postgres password=postgres sslmode=disable
  dir: migrations
  table: migrations

test:
  dialect: postgres
  datasource: host=localhost dbname=postgres_test user=postgres password=postgres sslmode=disable
  dir: migrations
  table: migrations 